### ISSUE TITLE
Moving elements in a compendium using folders causes the view to reset at the wrong position.

### ISSUE THREAD

**Issue by FrankIsAtank** [earlSt1/vtt-compendium-folders#194]
When moving elements from one folder to another, the view shifts by a number of elements equal to the number of folders present in the compendium.

**Comment by FrankIsAtank** [comment]
Foundry VTT 10
DnD5e 2.1.2
Compendium Folder 2.5.6

**Comment by earlSt1** [comment]
Hi, unfortunately I did look into this when creating the folders inside compendiums. Because the window renders again I'm not able to remember the scroll position. Since v11 is just round the corner (which should make this module redundant) I've not got plans to try and make a workaround for this.

I'll still include some way of migrating from CF to the core Foundry folders though!
