### ISSUE TITLE
Would this work with published map pack modules?

### ISSUE THREAD

**Issue by baileywick** [earlSt1/vtt-compendium-folders#38]
I publish a number of free and premium modules for Foundry under the Baileywiki moniker. My module Compendiums are getting quite extensive particularly with the recent Modular City System. Organization is becoming a challenge for me and for users of my packs.

I'm wondering if I could use your module to organize my Compendiums, and if that organization scheme (folders, etc) would travel with my Compendiums as I publish them to the public.

That is, would my users also get that organization scheme as long as they have your module installed?

**Comment by earlSt1** [comment]
They would indeed. The SWADE core rules package uses compendium folders as a dependency and organises the contents of the compendum.

So long as it's for non-commercial use, then all you would need to do is construct a folder structure using the features this module provides, then include that compendium in your module and add compendium folders as a dependency. 

The way the module "creates" folders in the compendium is by creating temporary entities with folder data associated with them. The module then parses these temporary entities and creates elements in the compendium window. If you dont have the module installed then the temporary entities would be visible, but otherwise the compendium will function correctly.

Also love your map packs btw, cant wait til my players reach a city so I can play around with the modular city tiles :smile:

**Comment by baileywick** [comment]
Awesome. Glad you like my stuff. If I end up using your module, I'll be
happy to give you free access just so you get to see how I'm using your
stuff.

Ok, so my subscribers are paid subscribers. Does that trigger "commercial
use" for you, or is it just that I don't try to resell your module
explicitly, or how does that work?

**Comment by earlSt1** [comment]
Ah right ok, sorry didnt realise how your module worked. I've got so many map packs installed haha.

I'll ping you a message on discord so we can discuss there. I'll also close this issue for now as the question has been answered :smile:
